src/Intranet/Intranet.UI/Controllers/NoticiasController.cs
using Intranet.Data.Entities;
using Simple.ImageResizer;
using System;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Intranet.UI.Controllers
{
    [Authorize(Roles = "Noticias,Noticias-Admin")]
    public class NoticiasController : BaseController
    {
        public NoticiasController()
        {
            ViewBag.Categorias = _banco.NoticiasCategorias.OrderBy(e => e.Nome).ToList();

            ViewBag.Title = "Notícias";
        }

        // GET: Noticias
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Lista(string busca, int? idCategoria)
        {
            var noticias = _banco.Noticias.AsQueryable();

            if (!string.IsNullOrEmpty(busca))
            {
                noticias = noticias.Where(l => l.Titulo.Contains(busca) || l.Texto.Contains(busca));
            }

            if (idCategoria != null)
            {
                noticias = noticias.Where(l => l.IdCategoria == idCategoria);
            }
            return PartialView(noticias.OrderByDescending(l => l.Data).ToList());
        }

        public void Excluir(int id)
        {
            var item = _banco.Noticias.Find(id);
            if (item == null)
            {
                throw new ArgumentException("Item inválido");
            }

            _banco.Noticias.Remove(item);
            _banco.SaveChanges();
        }

        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Novo(Noticia model, HttpPostedFileBase foto, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (foto != null)
                {
                    MemoryStream target = new MemoryStream();
                    foto.InputStream.CopyTo(target);
                    var imageResizer = new ImageResizer(target.ToArray());
                    //imageResizer.Resize(237, 139, ImageEncoding.Png);
                    var nomeFoto = DateTime.Now.ToString("yyyyMMddHHmmss") + foto.FileName;
                    imageResizer.SaveToFile(Path.Combine(Server.MapPath("~/Content/Noticias/"), nomeFoto));

                    model.Imagem = nomeFoto;
                }

                if (file != null)
                {
                    var fileName = DateTime.Now.ToString("yyyyMMddHHmmss") + Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Noticias/"), fileName);
                    file.SaveAs(path);

                    model.Arquivo = fileName;
                }

                _banco.Noticias.Add(model);
                _banco.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Editar(int id)
        {
            var noticia = _banco.Noticias.Find(id);
            if (noticia == null)
            {
                return RedirectToAction("Index");
            }

            return View(noticia);
        }

        public FileResult Download(string arquivo)
        {
            if (arquivo.Contains("../"))
            {
                throw new ArgumentException("Arquivo inválido");
            }
            var caminho = Server.MapPath("~/Content/Noticias/") + arquivo;
            var file = new FileInfo(caminho);

            var extensoesPermitidas = ".jpg,.jpeg,.png,.gif,.pdf,.doc,.docx,.txt,.odt,.rtf,.xls,.xlsx,.ai,.eps";

            if (file.Exists)
            {
                var extensao = file.Extension;

                if (extensoesPermitidas.ToLower().Contains(extensao.ToLower()))
                {
                    return File("~/Content/Noticias/" + arquivo, System.Net.Mime.MediaTypeNames.Application.Octet, arquivo);
                }
            }
            throw new ArgumentException("Arquivo inválido");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Editar(Noticia model, HttpPostedFileBase foto, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (foto != null)
                {
                    MemoryStream target = new MemoryStream();
                    foto.InputStream.CopyTo(target);
                    var imageResizer = new ImageResizer(target.ToArray());
                    //imageResizer.Resize(237, 139, ImageEncoding.Png);
                    var nomeFoto = DateTime.Now.ToString("yyyyMMddHHmmss") + foto.FileName;
                    imageResizer.SaveToFile(Path.Combine(Server.MapPath("~/Content/Noticias/"), nomeFoto));

                    model.Imagem = nomeFoto;
                }

                if (file != null)
                {
                    var fileName = DateTime.Now.ToString("yyyyMMddHHmmss") + Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Noticias/"), fileName);
                    file.SaveAs(path);

                    model.Arquivo = fileName;
                }

                _banco.Noticias.AddOrUpdate(model);
                _banco.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Detalhes(int id)
        {
            var noticia = _banco.Noticias.Find(id);
            if (noticia == null)
            {
                return RedirectToAction("Index");
            }

            ViewBag.Recomendado = _banco.Noticias.Where(c => c.IdCategoria == noticia.IdCategoria && c.Id != noticia.Id).OrderByDescending(n => n.Data).Take(4).ToList();

            return View(noticia);
        }

        public ActionResult NovaFoto()
        {
            return View();
        }
    }
}

src/Intranet/Intranet.UI/Views/Noticias/Detalhes.cshtml
@using Intranet.Data.Entities
@using Intranet.UI.Util
@model Noticia
<section class="content-noticias">
    <div class="info-interna">
        @if (User.IsInRole("Noticias-Admin"))
        {
            <div class="edits">
                <div class="icon-edits"></div>
                <div class="subedit">
                    <div class="btnEditar" data-link="@Url.Action("Editar", "Noticias", new {Model.Id})">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>Editar
                    </div>
                    <div class="btnExcluir" data-link="@Url.Action("Excluir", "Noticias", new {Model.Id})">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>Excluir
                    </div>
                </div>
            </div>
        }
        <p class="date">@Model.Data.ToString("dd 'de' MMMM 'de' yyyy")</p>
        <p class="title">@Model.Titulo</p>
        <div class="category">@Model.Categoria.Nome</div>
        @if (!string.IsNullOrEmpty(Model.Imagem))
        {
            <img src="/Content/Noticias/@Model.Imagem" alt="@Model.Titulo">
        }
        @Html.Raw(Model.Texto)

        @if (!string.IsNullOrEmpty(Model.Arquivo))
        {
            <div class="anexos">
                <p><strong>Anexo</strong></p>
                <div class="list-news list-arquivos">

                        <div class="item">
                            <div class="topo">
                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
                                <p>@Html.TamanhoAnexoNoticia(Model.Arquivo)</p>
                            </div>
                            <div class="info">
                                <p>@Model.Data.ToString("dd 'de' MMMM 'de' yyyy")</p>
                                <p class="title">@Model.Arquivo</p>
                                <a href="@Url.Action("Download", new {arquivo = Model.Arquivo})"><button>download</button></a>
                            </div>
                        </div>
                </div>
            </div>
        }
    </div>
    @if (((IEnumerable<Noticia>)ViewBag.Recomendado).Any())
    {
        <h4>Recomendado</h4>
        <div class="list-news">
            @foreach (Noticia noticia in ViewBag.Recomendado)
            {
                <article @if (!string.IsNullOrEmpty(noticia.Imagem))
                         {
                             @Html.Raw("class='image' data-imagem='"+noticia.Imagem+"'");
                         }>
                    <a href="@Url.Action("Detalhes", "Noticias", new { id = noticia.Id })">
                        <div class="info">
                            <p class="date">@noticia.Data.ToString("dd 'de' MMMM 'de' yyyy")</p>
                            <p class="title">@noticia.Titulo</p>
                            <div class="category">@noticia.Categoria.Nome</div>
                        </div>
                    </a>
                </article>
            }
        </div>
    }
</section>
@section scripts{
    <script>
        $(".image").each(function() {
            $(this).css("background-image", "url('/Content/Noticias/" + $(this).data("imagem") + "')");
        });
    </script>
}

src/Intranet/Intranet.UI/Views/Noticias/Editar.cshtml
@model Intranet.Data.Entities.Noticia
<section class="content-internas">
    <div class="info-interna">
        <form class="formulario-base" method="post" action="@Url.Action("Editar", "Noticias")" enctype="multipart/form-data">
            @Html.HiddenFor(n => n.Id)
            @Html.HiddenFor(n => n.Imagem)
            @Html.HiddenFor(n => n.Arquivo)
            <div class="container">
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Titulo)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.TextBoxFor(m => m.Titulo)
                        @Html.ValidationMessageFor(m => m.Titulo)
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.IdCategoria)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.DropDownListFor(m => m.IdCategoria, new SelectList(ViewBag.Categorias, "Id", "Nome"), "Selecione")
                        @Html.ValidationMessageFor(m => m.IdCategoria)
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Texto)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.TextAreaFor(m => m.Texto)
                        @Html.ValidationMessageFor(m => m.Texto)
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Imagem)
                    </div>
                    <div class="col l9 m8 s12">
                        @if (!string.IsNullOrEmpty(Model.Imagem))
                        {
                            <div class="legenda"><strong>Atual:</strong> <a target="_blank" href="/Content/Noticias/@Model.Imagem">@Model.Imagem</a></div>
                        }
                        <input type="file" name="Foto" id="Foto" value="" accept=".jpg,.jpeg,.png,.gif" />
                        @Html.ValidationMessageFor(m => m.Imagem)
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        <label for="Destaque">
                            Destaque
                        </label>
                    </div>
                    <div class="col l9 m8 s12">
                        <div class="list-check">
                            <div class="col l6 m12 s12">
                                <div class="item">
                                    <label for="Destaque">
                                        @Html.CheckBoxFor(m => m.Destaque) DEFINIR COMO DESTAQUE NA TELA INICIAL
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Arquivo)
                    </div>
                    <div class="col l9 m8 s12">
                        @if (!string.IsNullOrEmpty(Model.Arquivo))
                        {
                            <div class="legenda"><strong>Atual:</strong> <a target="_blank" href="/Content/Noticias/@Model.Arquivo">@Model.Arquivo</a></div>
                        }
                        <input type="file" name="File" id="File" value="" accept=".jpg,.jpeg,.png,.gif,.pdf,.doc,.docx,.txt,.odt,.rtf,.xls,.xlsx,.ai,.eps" />
                        @Html.ValidationMessageFor(m => m.Arquivo)
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Data)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.TextBoxFor(m => m.Data, new { type = "text", @class = "data" })
                        @Html.ValidationMessageFor(m => m.Data)
                    </div>
                </div>
                <div class="list-botoes">
                    <button class="btn-form red" type="submit">
                        <i class="fa fa-floppy-o" aria-hidden="true"></i>Salvar
                    </button>
                    <button class="btn-form" type="reset">
                        <i class="fa fa-times" aria-hidden="true"></i>Cancelar
                    </button>
                </div>
            </div>
        </form>
    </div>
</section>
@section scripts
{
    <script type="text/javascript" src="~/libs/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="~/libs/ckeditor/sample.js"></script>
    <script>
        initSample("Texto");

        $("#Foto").change(function () {
            var fileExtension = [
                'jpg', 'jpeg', 'png', 'gif'
            ];
            var arquivos = $("#Foto")[0].files;
            $.map(arquivos, function (val) {
                if ($.inArray(val.name.split('.').pop().toLowerCase(), fileExtension) == -1) {
                    swal('Oops...', 'São permitidos apenas os formatos: ' + fileExtension.join(', '), 'error');
                    $("#Foto").val('');
                }
            });
        });

        $("#File").change(function () {
            var fileExtension = [
                'jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'txt', 'odt', 'rtf', 'xls', 'xlsx', 'ai', 'eps'
            ];
            var arquivos = $("#File")[0].files;
            $.map(arquivos, function (val) {
                if ($.inArray(val.name.split('.').pop().toLowerCase(), fileExtension) == -1) {
                    swal('Oops...', 'São permitidos apenas os formatos: ' + fileExtension.join(', '), 'error');
                    $("#File").val('');
                }
            });
        });
    </script>
}

src/Intranet/Intranet.UI/Views/Noticias/Novo.cshtml
@model Intranet.Data.Entities.Noticia
<section class="content-internas">
    <div class="info-interna">
        <p style="font-size: 12px; margin-bottom: 20px;">Os campos assinalados com * são de preenchimento obrigatório</p>
        <form class="formulario-base" method="post" action="@Url.Action("Novo", "Noticias")" enctype="multipart/form-data">
            <div class="container">
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Titulo)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.TextBoxFor(m => m.Titulo)
                        @Html.ValidationMessageFor(m => m.Titulo)
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.IdCategoria)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.DropDownListFor(m => m.IdCategoria, new SelectList(ViewBag.Categorias, "Id", "Nome"), "Selecione")
                        @Html.ValidationMessageFor(m => m.IdCategoria)
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Texto)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.TextAreaFor(m => m.Texto)
                        @Html.ValidationMessageFor(m => m.Texto)
                    </div>
                </div>

                <div class="row">
                    <div class="col l3 m4 s12">
                        <label for="Destaque">
                            Destaque
                        </label>
                    </div>
                    <div class="col l9 m8 s12">
                        <div class="list-check">
                            <div class="col l6 m12 s12">
                                <div class="item">
                                    <label for="Destaque">
                                        @Html.CheckBoxFor(m => m.Destaque) DEFINIR COMO DESTAQUE NA TELA INICIAL
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Imagem)
                    </div>
                    <div class="col l9 m8 s12">
                        <input type="file" name="Foto" id="Foto" value="" accept=".jpg,.jpeg,.png,.gif" />
                        @Html.ValidationMessageFor(m => m.Imagem)
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Arquivo)
                    </div>
                    <div class="col l9 m8 s12">
                        <input type="file" name="File" id="File" value="" accept=".jpg,.jpeg,.png,.gif,.pdf,.doc,.docx,.txt,.odt,.rtf,.xls,.xlsx,.ai,.eps" />
                        @Html.ValidationMessageFor(m => m.Arquivo)
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Data)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.TextBoxFor(m => m.Data, new { type = "text", @class = "data" })
                        @Html.ValidationMessageFor(m => m.Data)
                    </div>
                </div>

             

                <div class="list-botoes">
                    <button class="btn-form red" type="submit">
                        <i class="fa fa-floppy-o" aria-hidden="true"></i>Salvar
                    </button>
                    <button class="btn-form" type="reset">
                        <i class="fa fa-times" aria-hidden="true"></i>Cancelar
                    </button>
                </div>
            </div>
        </form>
    </div>
</section>
@section scripts
{
    <script type="text/javascript" src="~/libs/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="~/libs/ckeditor/sample.js"></script>
    <script>
        initSample("Texto");

        $("#Foto").change(function () {
            var fileExtension = [
                'jpg', 'jpeg', 'png', 'gif'
            ];
            var arquivos = $("#Foto")[0].files;
            $.map(arquivos, function (val) {
                if ($.inArray(val.name.split('.').pop().toLowerCase(), fileExtension) == -1) {
                    swal('Oops...', 'São permitidos apenas os formatos: ' + fileExtension.join(', '), 'error');
                    $("#Foto").val('');
                }
            });
        });

        $("#File").change(function () {
            var fileExtension = [
                'jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'txt', 'odt', 'rtf', 'xls', 'xlsx', 'ai', 'eps'
            ];
            var arquivos = $("#File")[0].files;
            $.map(arquivos, function (val) {
                if ($.inArray(val.name.split('.').pop().toLowerCase(), fileExtension) == -1) {
                    swal('Oops...', 'São permitidos apenas os formatos: ' + fileExtension.join(', '), 'error');
                    $("#File").val('');
                }
            });
        });
    </script>
}