template/intranet-template-1-0-0/Controllers/PerfisController.cs
using $safeprojectname$.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace $safeprojectname$.Controllers
{
    public class PerfisController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private ApplicationGroupManager _groupManager;

        public ApplicationGroupManager GroupManager
        {
            get
            {
                return _groupManager ?? new ApplicationGroupManager();
            }
            private set
            {
                _groupManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;

        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext()
                           .Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        public PerfisController()
        {
            ViewBag.Area = "Gestão do Sistema";
            ViewBag.Title = "Gerenciar Perfis";
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Lista(string busca)
        {
            var perfis = GroupManager.Groups;
            if (!string.IsNullOrEmpty(busca))
            {
                perfis = perfis.Where(p => p.Name.Contains(busca) || p.Description.Contains(busca));
            }
            return PartialView(perfis.ToList());
        }

        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationgroup =
                await this.GroupManager.Groups.FirstOrDefaultAsync(g => g.Id == id);
            if (applicationgroup == null)
            {
                return HttpNotFound();
            }
            var groupRoles = this.GroupManager.GetGroupRoles(applicationgroup.Id);
            string[] RoleNames = groupRoles.Select(p => p.Name).ToArray();
            ViewBag.RolesList = RoleNames;
            ViewBag.RolesCount = RoleNames.Count();
            return View(applicationgroup);
        }

        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(
            [Bind(Include = "Name,Description")] ApplicationGroup applicationgroup, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                applicationgroup.Data = DateTime.Now;
                // Create the new Group:
                var result = await this.GroupManager.CreateGroupAsync(applicationgroup);
                if (result.Succeeded)
                {
                    selectedRoles = selectedRoles ?? new string[] { };

                    // Add the roles selected:
                    await this.GroupManager.SetGroupRolesAsync(applicationgroup.Id, selectedRoles);
                }
                return RedirectToAction("Index");
            }

            // Otherwise, start over:
            ViewBag.RoleId = new SelectList(
                this.RoleManager.Roles.ToList(), "Id", "Name");
            return View("Novo", applicationgroup);
        }

        public async Task<ActionResult> Editar(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationgroup = await this.GroupManager.FindByIdAsync(id);
            if (applicationgroup == null)
            {
                return HttpNotFound();
            }

            // Get a list, not a DbSet or queryable:
            var groupRoles = await this.GroupManager.GetGroupRolesAsync(id);

            var model = new GroupViewModel()
            {
                Id = applicationgroup.Id,
                Name = applicationgroup.Name,
                Description = applicationgroup.Description
            };

            // load the roles/Roles for selection in the form:
            foreach (var Role in groupRoles)
            {
                var listItem = new SelectListItem()
                {
                    Text = Role.Name,
                    Value = Role.Id,
                    Selected = true
                };
                model.RolesList.Add(listItem);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(
            [Bind(Include = "Id,Name,Description")] GroupViewModel model, params string[] selectedRoles)
        {
            var group = await this.GroupManager.FindByIdAsync(model.Id);
            if (group == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                group.Name = model.Name;
                group.Description = model.Description;
                await this.GroupManager.UpdateGroupAsync(group);

                selectedRoles = selectedRoles ?? new string[] { };
                await this.GroupManager.SetGroupRolesAsync(group.Id, selectedRoles);
                return RedirectToAction("Index");
            }
            return View("Editar", model);
        }

        [HttpPost]
        public void Excluir(string id)
        {
            if (id == null)
            {
                throw new ArgumentException("Item inválido");
            }
            ApplicationGroup applicationgroup = GroupManager.FindById(id);
            GroupManager.DeleteGroup(id);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

template/intranet-template-1-0-0/Views/Perfis/Editar.cshtml
@using $safeprojectname$.Models
@using $safeprojectname$.Util
@model GroupViewModel
<section>
    <div class="info-interna">
        <form class="formulario-base" method="post" action="@Url.Action("Edit", "Perfis")">
            @Html.HiddenFor(m=>m.Id)
            <div class="container">
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Name)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.TextBoxFor(m => m.Name)
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Description)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.TextAreaFor(m => m.Description)
                        @Html.ValidationMessageFor(m => m.Description)
                    </div>
                </div>
                <!-- Selecione as Permissôes -->
                <div class="row">
                    <div class="col l3 m4 s12">
                        <label for="gerenciarperfil-descricao">
                            Selecione as Permissôes:
                        </label>
                    </div>
                    <div class="col l9 m8 s12 blocopermisoes">
                        <div class="row">
                            <div class="col l4 s12">
                                <div class="ptitle">
                                    <p>permissão</p>
                                </div>
                            </div>
                            <div class="col l4 s12">
                                <div class="ptitle">
                                    <p>Visualizar</p>
                                </div>
                            </div>
                            <div class="col l4 s12">
                                <div class="ptitle">
                                    <p>Administrar <span>(Cadastrar, Editar e Excluir)</span>
                                    </p>
                                </div>
                            </div>
                        </div>
                        @foreach (AreasEnum area in Enum.GetValues(typeof(AreasEnum)))
                        {
                            <div class="row list-check">
                                <div class="col l4 s12">
                                    <p>@Html.EnumDisplayNameFor(area)</p>
                                </div>
                                <div class="col l4 s12">
                                    <div class="item">
                                        <label>
                                            <input type="checkbox" name="SelectedRoles" value="@area.ToString()"> Visualizar
                                        </label>
                                    </div>
                                </div>
                                <div class="col l4 s12">
                                    <div class="item">
                                        <label>
                                            <input type="checkbox" name="SelectedRoles" value="@(area + "-Admin")"> Administrar
                                        </label>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>

                <div class="list-botoes">
                    <button class="btn-form red" type="submit">
                        <i class="fa fa-floppy-o" aria-hidden="true"></i>Salvar
                    </button>
                    <button class="btn-form" type="reset">
                        <i class="fa fa-times" aria-hidden="true"></i>Cancelar
                    </button>
                </div>
            </div>
        </form>
    </div>
</section>
@section scripts
{
    <script>
        @foreach (var role in Model.RolesList.ToList())
        {
            <text>$("input[type='checkbox'][value='@role.Text']").prop('checked', true);</text>
            @*<text>$("input[type='checkbox'][value='@role.Text']").parent().parent().addClass('ativo');</text>*@
        }

        $("input[type='checkbox']").change(function () {
            var role = $(this).val();
            if (role.indexOf("Admin") > 0) {
                if (this.checked) {
                    $("input[type='checkbox'][value='" + role.replace("-Admin", "") + "']").prop('checked', true);
                    $("input[type='checkbox'][value='" + role.replace("-Admin", "") + "']").parent().parent().addClass('ativo');
                }
            }
        });
    </script>
}

template/intranet-template-1-0-0/Views/Perfis/Index.cshtml
@if (User.IsInRole("Perfis-Admin"))
{
    <a href="@Url.Action("Novo", "Perfis")">
        <div class="buttoncolor btn-newlink">
            <i class="fa fa-plus-square" aria-hidden="true"></i>Novo perfil
        </div>
    </a>
}
<section class="content-linksuteis">
    <div class="filters">
        <div class="container">
            <form action="/" method="post" id="frmBuscaPerfis">
                <div class="row">
                    <div class="col m10 s12">
                        <input type="text" name="Busca" id="palavrachave" placeholder="Palavra-chave">
                    </div>
                    <div class="col m2 s12">

                        <button type="submit">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div id="divPerfis" style="min-height: 450px;">
    </div>
</section>
@section scripts
{
    <script src="~/js/perfis.js"></script>
    <script>
        perfis.init();
    </script>
}

template/intranet-template-1-0-0/Views/Perfis/Lista.cshtml
@model IEnumerable<$safeprojectname$.Models.ApplicationGroup>
@if (!Model.Any())
{
    <p>Nenhum perfil encontrado.</p>
}
else
{
    <p>Total de @Model.Count() perfis</p>
    <div class="list-links">
        @foreach (var perfil in Model)
        {
            <div class="item">
                <div class="iconlink">
                    <span>@perfil.Name.Substring(0, 2).ToUpper()</span>
                </div>
                <div class="info">
                    <p class="title">@perfil.Name</p>
                    <p class="subtit">Total de @perfil.ApplicationUsers.Count usuário(s) nesse perfil</p>
                    <p>Criado em @perfil.Data.ToShortDateString()</p>
                </div>
                @if (User.IsInRole("Perfis-Admin"))
                {
                    <div class="edits">
                        <div class="icon-edits"></div>
                        <div class="subedit">
                            <div class="btnEditar" data-link="@Url.Action("Editar", "Perfis", new {perfil.Id})">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>Editar
                            </div>
                            <div class="btnExcluir" data-link="@Url.Action("Excluir", "Perfis", new {perfil.Id})">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>Excluir
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
    </div>
    <div class="btn-carregarmais">
        <img src="~/images/btn-carregarmais.png" alt="">
    </div>
}

template/intranet-template-1-0-0/Views/Perfis/Novo.cshtml
@using $safeprojectname$.Models
@using $safeprojectname$.Util
@model $safeprojectname$.Models.ApplicationGroup
<section>
    <div class="info-interna">
        <p style="font-size: 12px; margin-bottom: 20px;">Os campos assinalados com * são de preenchimento obrigatório</p>
        <form class="formulario-base" method="post" action="@Url.Action("Create", "Perfis")">
            <div class="container">
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Name)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.TextBoxFor(m => m.Name)
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="row">
                    <div class="col l3 m4 s12">
                        @Html.LabelFor(m => m.Description)
                    </div>
                    <div class="col l9 m8 s12">
                        @Html.TextAreaFor(m => m.Description)
                        @Html.ValidationMessageFor(m => m.Description)
                    </div>
                </div>
                <!-- Selecione as Permissôes -->
                <div class="row">
                    <div class="col l3 m4 s12">
                        <label for="gerenciarperfil-descricao">
                            Selecione as Permissôes:
                        </label>
                    </div>
                    <div class="col l9 m8 s12 blocopermisoes">
                        <div class="row">
                            <div class="col l4 s12">
                                <div class="ptitle"><p>permissão</p></div>
                            </div>
                            <div class="col l4 s12">
                                <div class="ptitle"><p>Visualizar</p></div>
                            </div>
                            <div class="col l4 s12">
                                <div class="ptitle"><p>Administrar <span>(Cadastrar, Editar e Excluir)</span></p></div>
                            </div>
                        </div>
                        @foreach (AreasEnum area in Enum.GetValues(typeof(AreasEnum)))
                        {
                            <div class="row list-check">
                                <div class="col l4 s12">
                                    <p>@Html.EnumDisplayNameFor(area)</p>
                                </div>
                                <div class="col l4 s12">
                                    <div class="item">
                                        <label>
                                            <input type="checkbox" name="SelectedRoles" value="@area.ToString()"> Visualizar
                                        </label>
                                    </div>
                                </div>
                                <div class="col l4 s12">
                                    <div class="item">
                                        <label>
                                            <input type="checkbox" name="SelectedRoles" value="@(area + "-Admin")"> Administrar
                                        </label>
                                    </div>
                                </div>
                            </div>                            
                        }
                    </div>
                </div>

                <div class="list-botoes">
                    <button class="btn-form red" type="submit">
                        <i class="fa fa-floppy-o" aria-hidden="true"></i>Salvar
                    </button>
                    <button class="btn-form" type="reset">
                        <i class="fa fa-times" aria-hidden="true"></i>Cancelar
                    </button>
                </div>
            </div>
        </form>
    </div>
</section>
@section scripts
{
    <script>
        $("input[type='checkbox']").change(function () {
            var role = $(this).val();
            if (role.indexOf("Admin") > 0) {
                if (this.checked) {
                    $("input[type='checkbox'][value='" + role.replace("-Admin", "") + "']").prop('checked', true);
                    $("input[type='checkbox'][value='" + role.replace("-Admin", "") + "']").parent().parent().addClass('ativo');
                }
            }
        });
    </script>
}